[package]
name = "mouscache_test"
version = "0.2.0"
authors = ["richer <richer.arc@gmail.com>"]
publish = false

[dependencies]

[dependencies.mouscache]
path = "../mouscache"

[dependencies.mouscache_derive]
path = "../mouscache_derive"