[package]
name = "mouscache_test"
version = "0.4.0"
authors = ["richer <richer.arc@gmail.com>"]
publish = false

[dependencies]

[dependencies.mouscache]
path = "../mouscache"
features = ["hashset"]

[dependencies.mouscache_derive]
path = "../mouscache_derive"