[package]
name = "mouscache_redis"
version = "0.2.0"
authors = ["richer <richer.arc@gmail.com>"]

[dependencies]
redis = "0.8"
dns-lookup = "0.9"

[dependencies.cache]
git = "https://github.com/wayk/mouscache-rs"