[package]
name = "mouscache_derive"
version = "0.2.0"
authors = ["Richer Archambault <richer.arc@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.4"
proc-macro2 = "0.2"


[dependencies.syn]
version = "0.12"
features = ["derive"]